<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8">
            <h1>About IGP</h1>
            <hr />
            <p>
                Social Media Marketing (SMM) is a form of internet marketing that comprises of several techniques that consider social networks as the platform to reach the targeted set of customers by spreading brand awareness through social media campaigns.
                Social media platforms such as Facebook, Google+, LinkedIn, Twitter, Pinterest, Tumblr, Instagram etc. offer plethora of opportunities to spread brand awareness or promote particular products through different kinds of social media marketing campaigns. These social networking websites are backed by certain social media marketing tools that help to track the results and accordingly alter the social media marketing strategies so as to establish a strong social media presence.
                So, if you too wish to know more about some of the major Social Media Marketing (SMM) tools, read on:
            </p>
        </div>
    </div>
</div>