<div class="container" style="max-width: 500px; min-width: 250px;">

    <form class="form-signin">
        <h2 class="form-signin-heading">Create your personal account</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" style="border-bottom-left-radius: 0px; border-bottom-right-radius: 0px;" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
        <label for="inputPassword" class="sr-only">First Name</label>
        <input type="text" style="border-radius: 0px; border-top: 0px" id="inputPassword" class="form-control" placeholder="First Name" required="">
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" style="border-radius: 0px; border-top: 0px" id="inputPassword" class="form-control" placeholder="Password" required="">
        <button class="btn btn-lg btn-success btn-block" style="border-top-left-radius: 0px; border-top-right-radius: 0px;" type="submit">Sign up</button>
    </form>

</div>