<?php
/**
 * Created by PhpStorm.
 * User: b.akhmedov
 * Date: 06.11.18
 * Time: 13:59
 */

namespace Auth\Controller;

use Application\Model\Base;
use Auth\Helpers\Session;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;

class AuthController extends AbstractActionController
{
    private $users;

    private $session;

    function __construct(Base $users, Session $session)
    {
        $this->users = $users;
        $this->session = $session;
    }

    function onDispatch(MvcEvent $e)
    {
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }

    public function loginAction()
    {
        if ($this->getRequest()->isPost()) {
            try {
                $email = $this->params()->fromPost('login_email');
                $password = $this->params()->fromPost('login_password');
                $user = $this->users->getOnly(['email' => $email, 'password' => $password]);
                
                if(!empty($user['id'])){
                    $this->session->setUserId($user['id']);
                    $this->session->start();
                }

                return $this->redirect()->toRoute('admin');

            } catch (\Exception $e) {

            }
        }
        return $this->redirect()->toRoute('igp', [ 'action' => 'login' ], [ 'query' => ['error' => 'on'] ]);
    }

    public function logoutAction()
    {
        echo "LOGOUT";

        die();
    }
}