<!DOCTYPE html>
<html lang="en">
<head>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0">
        <style>
            /*HACK FOR IOS (iphone ipad etc)*/
            table
            {
                table-layout: fixed;
                max-width: 100%;
                width: 100%;
                word-break: break-all;
            }
        </style>
        <title>Edmin</title>

        <script src="/static/edmin/scripts/jquery-1.9.1.min.js" type="text/javascript"></script>
        <script src="/static/edmin/scripts/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
        <script src="/static/edmin/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/static/edmin/scripts/flot/jquery.flot.js" type="text/javascript"></script>
        <script src="/static/edmin/scripts/flot/jquery.flot.categories.js" type="text/javascript"></script>

        <script src="/static/edmin/scripts/flot/jquery.flot.resize.js" type="text/javascript"></script>
        <script src="/static/edmin/scripts/datatables/jquery.dataTables.js" type="text/javascript"></script>
        <script src="/static/edmin/scripts/common.js" type="text/javascript"></script>

        <script type="text/javascript" src="/static/map/js/jquery.vmap.js"></script>
        <script type="text/javascript" src="/static/map/js/maps/jquery.vmap.world.js" charset="utf-8"></script>
        <script type="text/javascript" src="/static/map/js/jquery.vmap.sampledata.js"></script>

        <link href="/static/map/css/jqvmap.css" media="screen" rel="stylesheet" type="text/css"/>

        <link type="text/css" href="/static/edmin/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link type="text/css" href="/static/edmin/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
        <link type="text/css" href="/static/edmin/css/theme.css" rel="stylesheet">
        <link type="text/css" href="/static/edmin/images/icons/css/font-awesome.css" rel="stylesheet">
        <link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600'
            rel='stylesheet'>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                        <i class="icon-reorder shaded"></i></a><a class="brand" href="index.html"><b style="color: rgb(40, 167, 69); ">IGP</b>. <small>pw</small> </a>
                    <div class="nav-collapse collapse navbar-inverse-collapse">
                        <ul class="nav nav-icons">
                            <li class="active"><a href="#"><i class="icon-envelope"></i></a></li>
                            <li><a href="#"><i class="icon-eye-open"></i></a></li>
                            <li><a href="#"><i class="icon-bar-chart"></i></a></li>
                        </ul>
                        <form class="navbar-search pull-left input-append" action="#">
                        <input type="text" class="span3">
                        <button class="btn" type="button">
                            <i class="icon-search"></i>
                        </button>
                        </form>
                        <?= $this->navigation('default')->menu()->setUlClass('nav pull-right') ?>
                    </div>
                    <!-- /.nav-collapse -->
                </div>
            </div>
            <!-- /navbar-inner -->
        </div>
        <!-- /navbar -->
        <div class="wrapper">
            <div class="container">
                <div class="row">
                    <div class="span3">
                        <div class="sidebar">
                            <?= $this->navigation('Zend\Navigation\Admin_links')->menu()->setUlClass('widget widget-menu unstyled') ?>
                        </div>
                        <!--/.sidebar-->
                    </div>
                    <!--/.span3-->
                    <div class="span9">
                        <?= $this->content ?>
                        <!--/.content-->
                    </div>
                    <!--/.span9-->
                </div>
            </div>
            <!--/.container-->
        </div>
        <!--/.wrapper-->
        <div class="footer">
            <div class="container">
                <b class="copyright">&copy; 2014 Edmin - EGrappler.com </b>All rights reserved.
            </div>
        </div>

    </body>
