<div class="content">
    <div class="btn-controls">
        <div class="btn-box-row row-fluid">
            <a href="#" style="background: #333333; color: #f4f3f0; " class="btn-box big span4"><i style="color: rgb(40, 167, 69); " class=" icon-random"></i><b style="color:whitesmoke;"><?=$totalLinks ?></b>
                <p class="text-muted">
                    Total links</p>
            </a><a href="#" style="background: #333333; color: #f4f3f0; " class="btn-box big span4"><i style="color: rgb(40, 167, 69); " class="icon-user"></i><b style="color:whitesmoke;">15</b>
                <p class="text-muted">
                    Frends</p>
            </a>
            </a><a href="#" style="background: #333333; color: #f4f3f0; " class="btn-box big span4"><i style="color: rgb(40, 167, 69); " class="icon-envelope"></i><b style="color:whitesmoke;">20</b>
                <p class="text-muted">
                    Messages</p>
            </a>
        </div>

    </div>
    <!--/#btn-controls-->



    <script>
        jQuery(document).ready(function () {
            jQuery('#vmap').vectorMap({
                map: 'world_en',
                backgroundColor: '#333333',
                borderColor: '#818181',
                borderOpacity: 0.25,
                borderWidth: 1,
                color: '#f4f3f0',
                colors: {<?=$colorMap ?>},
                enableZoom: true,
                hoverColor: '#c9dfaf',
                hoverOpacity: null,
                normalizeFunction: 'linear',
                scaleColors: ['#b6d6ff', '#005ace'],
                selectedColor: '#c9dfaf',
                selectedRegions: null,
                showTooltip: true,
                onRegionClick: function(element, code, region)
                {
                    var message = 'You clicked "'
                        + region
                        + '" which has the code: '
                        + code.toUpperCase();

                    alert(message);
                }
            });


        });
    </script>
    <div id="vmap" style="height: 600px;"></div>


    <br />

    <div class="module">
        <div class="module-head">
            <h3>Activity links for the last 5 days</h3>
        </div>
        <div class="module-body">
            <div class="chart inline-legend grid">
                <div id="placeholder2" class="graph" style="height: 500px">
                </div>
            </div>
        </div>
    </div>
    <!--/.module-->
    <div class="module hide">
        <div class="module-head">
            <h3>
                Adjust Budget Range</h3>
        </div>
        <div class="module-body">
            <div class="form-inline clearfix">
                <a href="#" class="btn pull-right">Update</a>
                <label for="amount">
                    Price range:</label>
                &nbsp;
                <input type="text" id="amount" class="input-" />
            </div>
            <hr />
            <div class="slider-range">
            </div>
        </div>
    </div>
    <div class="module">
        <div class="module-head">
            <h3>Activity</h3>
        </div>
        <div class="module-body table">
            <table cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped	 display"
                   width="100%">
                <thead>
                <tr>
                    <th>
                        Date time
                    </th>
                    <th>
                        Country
                    </th>
                    <th>
                        City
                    </th>
                    <th>
                        Platform
                    </th>
                    <th>
                        Browser
                    </th>
                </tr>
                </thead>
                <tbody>

                <?php foreach($fl_table as $item):?>
                <tr class="gradeU">
                    <td>
                        <?= date("d-m-Y", strtotime($item['date_time'])); ?>
                    </td>
                    <td>
                        <?= $item['country'] ?>
                    </td>
                    <td class="center">
                        <?= $item['city'] ?>
                    </td>
                    <td>
                        <?= $item['platform'] ?>
                    </td>

                    <td class="center">
                        <?= $item['browser'] ?>
                    </td>
                </tr>
                <?php endforeach; ?>
                </tbody>
                <tfoot>
                <tr>
                    <th>
                        Date time
                    </th>
                    <th>
                        Country
                    </th>
                    <th>
                        City
                    </th>
                    <th>
                        Platform
                    </th>
                    <th>
                        Browser
                    </th>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
    <!--/.module-->
</div>