
        <?php if(!empty($historys)): ?>
            <table class="table">
                <thead>
                <tr>
                    <th>Date</th>
                    <th>Link</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($historys as $item): ?>
                    <tr id="item_tr_<?=$item['id'] ?>" >
                        <td> <?= $item['date_time'] ?> </td>
                        <td><a href="<?= $item['source'] ?>" target="_blank"><?= $item['new'] ?></a></td>
                        <td>
                            <div  style="float: right;" class="btn-group" role="group">
                                <a href="<?=$this->url('admin', ['action' => 'linkinfo', 'id' => $item['id']])?>" id="adm_infoLink" class="btn btn-info" role="button" aria-pressed="true">Info</a>
                                <button id="<?=$item['id'] ?>" type="button" class="btn btn-danger adm_deleteLink" >Delete</button>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>


<script>
    $(function () {


        //---Delete button---
        $('.adm_deleteLink').on('click', function () {
            var link_id = $(this).attr('id');
            if (link_id > 0) {
                $.get("/admin/delete/" + link_id, function (data) {
                    if (data == '1') {
                        $("#item_tr_" + link_id).remove();
                    } else {
                        alert(data);
                    }
                });

            }
        });
        //--------------------
    });

</script>