<div class="content">
    <div class="btn-controls">
        <div class="btn-box-row row-fluid">
            <a href="#" style="background: #333333; color: #f4f3f0; " class="btn-box big span4"><i style="color: rgb(40, 167, 69); " class=" icon-random"></i><b style="color:whitesmoke;"><?=$totalLinks ?></b>
                <p class="text-muted">
                    Total links</p>
            </a><a href="#" style="background: #333333; color: #f4f3f0; " class="btn-box big span4"><i style="color: rgb(40, 167, 69); " class="icon-user"></i><b style="color:whitesmoke;">15</b>
                <p class="text-muted">
                    Frends</p>
            </a>
            </a><a href="#" style="background: #333333; color: #f4f3f0; " class="btn-box big span4"><i style="color: rgb(40, 167, 69); " class="icon-envelope"></i><b style="color:whitesmoke;">20</b>
                <p class="text-muted">
                    Messages</p>
            </a>
        </div>
    </div>
    <div class="module">
        <div class="module-head">
            <?php include __DIR__.'/mod_history.phtml' ?>
        </div>
    </div>
</div>