<div class="content">
    <div class="btn-controls">
        <div class="btn-box-row row-fluid">
            <a href="#" style="background: #333333; color: #f4f3f0; " class="btn-box big span4"><i style="color: rgb(40, 167, 69); " class=" icon-random"></i><b style="color:whitesmoke;"><?=$totalLinks ?></b>
                <p class="text-muted">
                    Total links</p>
            </a><a href="#" style="background: #333333; color: #f4f3f0; " class="btn-box big span4"><i style="color: rgb(40, 167, 69); " class="icon-user"></i><b style="color:whitesmoke;">15</b>
                <p class="text-muted">
                    Frends</p>
            </a>
            </a><a href="#" style="background: #333333; color: #f4f3f0; " class="btn-box big span4"><i style="color: rgb(40, 167, 69); " class="icon-envelope"></i><b style="color:whitesmoke;">20</b>
                <p class="text-muted">
                    Messages</p>
            </a>
        </div>
    </div>

    <div class="module">
        <div class="module-body">
            <div class="profile-head media">
                <a href="#" class="media-avatar pull-left">
                    <img src="images/user.png">
                </a>
                <div class="media-body">
                    <h4>
                        User Name
                        <small>edit</small>
                    </h4>
                    <p class="profile-brief">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
                        Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                        unknown printer took a galley of type.
                    </p>
                    <div class="profile-details muted">
                        <a href="#" class="btn"><i class="icon-plus shaded"></i>Add photo </a>
                        <a href="#" class="btn"><i class="icon-envelope-alt shaded"></i>Send message </a>
                    </div>
                </div>
            </div>
            <ul class="profile-tab nav nav-tabs">
                <li class="active"><a href="#activity" data-toggle="tab">Photos</a></li>
                <li><a href="#friends" data-toggle="tab">Settings</a></li>
            </ul>
            <div class="profile-tab-content tab-content">
                <div class="tab-pane fade active in" id="activity">
                    <div class="stream-list">
                        <div class="media stream">
                            <div class="media-body" style="text-align: center">
                                <img width="700px" src="https://www.gettyimages.com/gi-resources/images/CreativeLandingPage/HP_Sept_24_2018/CR3_GettyImages-159018836.jpg">
                                <br /><br />
                                <img width="700px" src="https://www.gettyimages.com/gi-resources/images/CreativeLandingPage/HP_Sept_24_2018/CR3_GettyImages-159018836.jpg">
                                <br /><br />
                                <img width="700px" src="https://www.gettyimages.ie/gi-resources/images/Homepage/Hero/UK/CMS_Creative_164657191_Kingfisher.jpg">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>