<div class="container">
    <div class="row">

        <?php if(!empty($categories)): ?>
        <div class="col-lg-3 align-items-start">
            <div class="list-group-flush">
                <a href="#" class="list-group-item list-group-item-action disabled"><b>Категории</b></a>
                <a href="<?= $this->url('shop') ?>" class="list-group-item list-group-item-action">Все категории</a>
                <?php foreach ($categories as $category): ?>
                <a href="<?= $this->url('shop', ['id' => $category['id']]) ?>" class="list-group-item list-group-item-action"><?= $category['title'] ?></a>
                <?php endforeach; ?>
            </div>
        </div>
        <?php endif; ?>

        <div class="col-lg-9">
            <div class="row">
                <?php if($items->count() >= 1): ?>
                    <?php foreach ($items as $item): ?>
                    <div class="col-lg-4" style="padding-bottom: 30px">
                        <div class="card h-100">
                            <a href="#"><img class="card-img-top" src="<?= $item['image'] ? $item['image'] : "http://placehold.it/700x400"?>" alt=""></a>
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a href="<?= $this->url('product', ['id' => $item['id']]) ?>"><?= $item['title'] ?></a>
                                </h5>
                                <?php if (!empty($item['old_price'])): ?>
                                    <h5 class="old_price"
                                        style="text-decoration: line-through;"><?= $item['old_price'] . " " . $item['currency'] ?></h5>
                                <?php endif; ?>
                                <h3><?= $item['price']." ".$item['currency'] ?></h3>
                                <p class="card-text"><?= $item['description_short'] ?></p>

                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <button type="button" class="cart_add btn btn-sm btn-outline-danger" onclick="sendGetRequest('<?= $this->url('cart', ['action' => 'add', 'id' => $item['id']]) ?>');">Купить</button>
                                        <a href="<?= $this->url('product', ['id' => $item['id']]) ?>" role="button" class="btn btn-sm btn-outline-secondary">Подробнее</a>
                                    </div>
                                </div>
                            </div>

                            <div class="card-footer">
                                <small class="text-muted"><?= str_repeat("★ ", $item['rating'])?><?= str_repeat("☆ ", 5 - $item['rating'])?> </small>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                <?php else: ?>
                    <h5 class="text-muted">В данной котегории нет данных</h5>
                <?php endif; ?>
            </div>
        </div>

        <!--end of col-->

            <div class="col-lg-12">
                <?php
                // add at the end of the file after the table

                if ($this->items->count() > 1) {
                    echo $this->paginationControl(
                    // the paginator object
                        $this->items,
                        // the scrolling style
                        'sliding',
                        // the partial to use to render the control
                        'partial/paginator.phtml',
                        // the route to link to when a user clicks a control link
                        [
                            'route' => 'shop'
                        ]
                    );
                }
                ?>
            </div>

    </div>


</div>
