<div class="row justify-content-center">
    <!-- Image -->

    <div class="row">
    <div class="col-12 col-lg-6">
        <div class="card bg-light mb-3">
            <div class="card-body">
                <a href="" data-toggle="modal" data-target="#productModal">
                    <img class="img-fluid" src="<?= $item['image'] ? $item['image'] : "https://dummyimage.com/800x800/55595c/fff" ?>" >
                    <p class="text-center">Zoom</p>
                </a>
            </div>
        </div>
    </div>

    <!-- Add to cart -->
    <div class="col-12 col-lg-6 add_to_cart_block">
        <div class="card bg-light mb-3">
            <div class="card-body">
                <h1><?= $item['title'] ?></h1> <hr>

                <?php if (!empty($item['old_price'])): ?>
                    <p class="old_price" style="text-decoration: line-through;"><?= $item['old_price'] . " " . $item['currency'] ?></p>
                <?php endif; ?>
                <h5 class="price"><?= $item['price'] . " " . $item['currency'] ?>  <small style="float: right; color: darkgrey"> артикл: <?= !empty($item['article']) ? $item['article'] : $item['id'] ?></small></h5>
                <small class="text-muted"><?= str_repeat("★ ", $item['rating'])?><?= str_repeat("☆ ", 5 - $item['rating'])?> </small>
                <br ><br >
                <p>
                    <?= !empty($item['description']) ? $item['description'] : $item['description_short'] ?>
                </p>

                <form method="get" action="cart.html">
                    <a href="cart.html" class="btn btn-success btn-lg btn-block text-uppercase">
                        Добавить в карзину
                    </a>
                </form>


            </div>
        </div>
    </div>
    </div>
</div>